### ISSUE TITLE
15 tests fail during the first build

### ISSUE THREAD

**Issue by ProttayMondalAdhikari-eaton** [edgexfoundry-holding/app-functions-sdk-python#3]
Hi, I am new in this repository. 

Upon installation ... I tried to run` make test-sdk`

Most of the tests passed. But I had 15 fails. Is that an expected behavior? 

I have attached the log below. 

[LOG.txt](https://github.com/user-attachments/files/18102015/LOG.txt)

Thanks in advance.

**Comment by cloudxxx8** [comment]
@ProttayMondalAdhikari-eaton we've updated the README.  please follow it and try again.

**Comment by ProttayMondalAdhikari-eaton** [comment]
Confiriming that going back to 3.10.16 worked
